# This rule is not used by the project cloudcontinuum-orchestrator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to orchestrator.cloudcontinuum.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cloudcontinuum-orchestrator
    app.kubernetes.io/managed-by: kustomize
  name: placementrequest-viewer-role
rules:
- apiGroups:
  - orchestrator.cloudcontinuum.io
  resources:
  - placementrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - orchestrator.cloudcontinuum.io
  resources:
  - placementrequests/status
  verbs:
  - get
