apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-runner-role
  namespace: kubeflow-user-example-com # <-- NOTA: Questo è il namespace dall'errore
rules:
- apiGroups: ["kubeflow.org", "pipelines.kubeflow.org"]
  resources:
  - experiments
  - pipelines
  - pipelineversions
  - runs
  - scheduledworkflows
  - tasks
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]