apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-runner-binding
  namespace: kubeflow-user-example-com # <-- Namespace dell'errore
subjects:
- kind: ServiceAccount
  name: cloudcontinuum-orchestrator-controller-manager  # Il nome del tuo SA
  namespace: cloudcontinuum-orchestrator-system     # Il namespace dove vive il tuo SA
roleRef:
  kind: Role
  name: pipeline-runner-role # Il ruolo creato al punto 1
  apiGroup: rbac.authorization.k8s.io